
slug: palm2
description: |
  ## Why monitor PaLM 2?

  PaLM 2 can help analyse and explain potentially malicious scripts. By processing large amounts of health data and emerging research, Med-PaLM 2 can help monitor disease spread, predict trends, and propose effective interventions. This could significantly enhance the speed and precision of public health responses, ultimately contributing to better health outcomes at a population level.

  ### What’s included in the PaLM 2 quickstart?

  Install this quickstart to install preconfigured observability solutions:
  - Pre-configured alerts that are triggered when specific criteria are met.
  - Informative dashboards.

summary: |
   Gain actionable information from monitoring PaLM 2 to increase resource efficiency and cut costs.
icon: logo.png
level: New Relic
authors:
  - New Relic
title: PaLM2
dashboards:
  - langchain
alertPolicies:
  - langchain
documentation:
  - name: PaLM 2 installation docs
    description: |
      With New Relic PaLM 2, you can keep an eye on your PaLM 2 statistics in real time.
    url: https://docs.newrelic.com/
dataSourceIds:
  - langchain
keywords:
  - langchain
  - mlops
  - NR1_addData
  