
slug: pinecone
description: |
  ## Why monitor Pinecone?

  Monitoring Pinecone can help you detect and respond to faults or failures promptly. If there are issues with hardware, software, or the network, monitoring tools can alert your operations team, allowing them to take corrective actions before they impact users. You can also identify bottlenecks, latency issues, and resource constraints.
  
  Here are some key reasons why monitoring Pinecone is important:
  - Performance Optimization
  - Scalability Assessment
  - Fault Detection
  - Anomaly Detection
  - Capacity Planning
  - Cost Management
  - Predictive Maintenance
  - Resource Allocation
  - User Experience Improvement

  ### What’s included in the Pinecone quickstart?

  Install this quickstart to install preconfigured observability solutions:
  - A number of high-value alerts are available, including total error requests,request latency in seconds, and indexes).
  - Informative dashboards (vector count, unique metric dimensions and more).

summary: |
   Gain actionable information from monitoring Pinecone to increase resource efficiency and cut costs.
icon: logo.png
level: New Relic
authors:
  - New Relic
title: Pinecone
dashboards:
  - langchain-vectordb
alertPolicies:
  - langchain-vectordb
documentation:
  - name: LangChain Vector Database integration documentation
    description: |
     Implement monitoring and instrumentation for your LangChain Vector Database, and ensure that your LangChain Vector Database data is integrated into New Relic for effective performance analysis and insights.
    url: https://github.com/newrelic/nr-openai-observability
dataSourceIds:
  - langchain-vectordb
keywords:
  - langchain-vectordb
  - mlops
  - NR1_addData
  