slug: postfix
description: |
  ## Postfix queue performance monitoring

  Postfix monitoring involves tracking and analyzing metrics related to the performance, health, and security of a Postfix mail server. This includes monitoring the mail queue, message traffic, error logs, and security. It can also be used to set up dashboards and alerts for monitoring Postfix metrics in real-time. Proper monitoring of Postfix can ensure the smooth operation and security of the mail server.

  ### What should you look for in a Postfix dashboard?

  Postfix monitoring dashboards provide real-time statistics on mail queues, message traffic, resource utilization, error logs, and security.

  ### What’s included in the Postfix quickstart?

  Install this quickstart to install preconfigured observability solutions:
  - A number of high-value alerts are available, including bounced non-delivery notifications, connections lost, authentication fails, and connections timed out.
  - Informative dashboards (email delivery process, number of messages bounced and deferred, number of incoming connections, and more).

summary: |
   Monitor your Postfix with New Relic infrastructure agent and NRI-Flex configuration. Get real-time insights into email delivery and performance, including message flows, queue sizes, per-day traffic summaries, per-hour traffic records, and server load.
icon: logo.png
level: New Relic
authors:
  - New Relic
title: Postfix
dashboards:
  - postfix
alertPolicies:
  - postfix
documentation:
  - name: Postfix
    description: |
      Postfix is a well-known mail server that is used to route and deliver email messages across mail servers.
    url: >-
      https://docs.newrelic.com
dataSourceIds:
  - postfix
keywords:
  - postfix
  - mail server
  - infrastructure
