id: postfix
displayName: Postfix
description: |
  Monitor the performance metrics of your Postfix mail server in real-time with New Relic APM.
install:
  primary:
    link:
      url: https://docs.newrelic.com
icon: logo.png
