
slug: hugging-face
description: |
  ## Why monitor Hugging Face?

  Monitoring Hugging Face can refer to several different activities, depending on the context. Here are some reasons why you might want to monitor Hugging Face:

  - Model Updates
  - Security
  - Community Contribution
  - New Features and APIs
  - Bug Fixes

  ### What’s included in this quickstart?

  Hugging Face quickstart guide help users to get started with their natural language processing (NLP) models and tools.

summary: |
  Gain actionable information from monitoring Hugging Face to increase resource efficiency and cut costs.
icon: logo.png
level: New Relic
authors:
  - New Relic
title: Hugging Face
documentation:
  - name: Hugging Face installation docs
    description: |
      With New Relic Hugging Face, you can keep an eye on your Hugging Face statistics in real time.
    url: https://docs.newrelic.com/
dataSourceIds:
  - langchain
keywords:
  - langchain
  - mlops
  - NR1_addData
alertPolicies:
  - langchain
