
slug: azure-openai
description: |
  ## Why monitor Azure OpenAI?

  Monitoring provides detailed Azure OpenAI model usage KPIs and metrics, including prompt information and token statistics for usage traceability. API Management connects to all Azure resources via Azure Private Link.

  Monitoring Azure OpenAI is crucial for several reasons:

  - Performance Monitoring: Monitoring helps you ensure that your Azure OpenAI models are performing as expected. You can track metrics like response time, accuracy, and throughput to identify any performance issues and optimize resource allocation.
  - Resource Utilization: Monitoring helps you understand how your resources (e.g., CPU, memory, GPU) are being utilized. This information can guide you in scaling up or down based on demand, optimizing costs, and ensuring that your infrastructure is not underutilized or overburdened.
  - Usage Patterns: Monitoring can reveal how your applications are using Azure OpenAI. By analyzing usage patterns, you can identify which API endpoints are the most popular, which can help you prioritize improvements and allocate resources effectively.
  - Error Detection: Monitoring allows you to detect and respond to errors or anomalies in real-time. This is critical for maintaining a high-quality user experience. It can also help you identify issues in the Azure OpenAI API integration or your application code.
  - Feedback Loop: Monitoring can provide valuable feedback that can be used to fine-tune your AI models and improve their performance over time. This iterative process can lead to better AI-driven applications.

  ### What’s included in this quickstart?

  New Relic Azure OpenAI monitoring quickstart includes:
  - Pre-configured alerts that are triggered when specific criteria are met.
  - Tools to monitor your Azure OpenAI usage and save money on your bill.
  - Token usage metrics that tracks the number of tokens used in each request.
  - Informative dashboards (request count, request success rate, concurrent connections, and more. 

summary: |
  Monitor and enhanced security with your Azure OpenAI. Get real-time insights into Azure OpenAI resource utilization and security services.
icon: logo.png
level: New Relic
authors:
  - New Relic
title: Azure OpenAI
documentation:
  - name: LangChain Vector Database integration documentation
    description: |
      Implement monitoring and instrumentation for your LangChain Vector Database, and ensure that your LangChain Vector Database data is integrated into New Relic for effective performance analysis and insights.
    url: https://github.com/newrelic/nr-openai-observability
dataSourceIds:
  - langchain
keywords:
  - langchain
  - mlops
  - NR1_addData
dashboards:
  - langchain
alertPolicies:
  - langchain
