
slug: milvus
description: |
  ## Why monitor Milvus?

  Monitoring Milvus, an open-source vector database, is important for several reasons, primarily to ensure its performance, reliability, and security. Here are some key reasons why you should monitor Milvus:
  - Performance Optimization
  - Capacity Planning
  - Resource Efficiency
  - Fault Detection
  - Scaling
  - Security
  - Data Quality Assurance
  - Operational Insights
  - Compliance
  - User Experience

  ### What’s included in this quickstart?

  Milvus quickstart will help you in log analysis, metrics collection, alerting systems, and performance testing. By continuously monitoring Milvus, you can proactively address issues, optimize performance, and provide a reliable and efficient service to your users or applications.

summary: |
  Monitoring Milvus data enables you to have a deeper understanding of performance and its current situation, allowing you to make timely adjustments to resource allocation.
icon: logo.png
level: New Relic
authors:
  - New Relic
title: Milvus
documentation:
  - name: LangChain Vector Database integration documentation
    description: |
     Implement monitoring and instrumentation for your LangChain Vector Database, and ensure that your LangChain Vector Database data is integrated into New Relic for effective performance analysis and insights.
    url: https://github.com/newrelic/nr-openai-observability
dataSourceIds:
  - langchain-vectordb
keywords:
  - langchain-vectordb
  - mlops
  - NR1_addData
dashboards:
  - langchain-vectordb
alertPolicies:
  - langchain-vectordb
