
slug: zilliz
description: |
  ## Why should you monitor your usage of Zilliz?

  Monitor your vector searches on Zilliz to get visibility on what you send to Zilliz, responses retrieved from Zilliz, latency, usage and errors. 

   ### Track the query performance of your Vector DB
 Track the behavior of your vector stores. Monitor the latency, queries, the number of documents retrieved, and the content of the documents so that you can evaluate their relevance.
 
 ### Track your app:  
  By tracking key metrics like latency, throughput, error rates, and input & output, you can gain insights into your app's performance and identify areas of improvement.


  ### What’s included in this quickstart?

  The Zilliz quickstart installs preconfigured observability solutions, including:
  - High-value alerts that can help you identify and resolve problems early.
  - Informative dashboards that provide you with a visual representation of the performance of your systems and applications.

summary: |
  Gain actionable information from monitoring Zilliz to increase resource efficiency and cut costs.
icon: logo.png
level: New Relic
authors:
  - New Relic
title: Zilliz
documentation:
  - name: LangChain Vector Database integration documentation
    description: |
      Implement monitoring and instrumentation for your LangChain Vector Database, and ensure that your LangChain Vector Database data is integrated into New Relic for effective performance analysis and insights.
    url: https://github.com/newrelic/nr-openai-observability
dataSourceIds:
  - langchain-vectordb
keywords:
  - langchain-vectordb
  - mlops
  - NR1_addData
dashboards:
  - langchain-vectordb
alertPolicies:
  - langchain-vectordb
