
slug: zilliz
description: |
  ## Why monitor Zilliz?

  Monitoring Zilliz, a geospatial data analytics and AI platform, is essential for several reasons:

  - Performance Optimization: By tracking metrics such as query response times, resource utilization, and system load, you can identify bottlenecks and optimize configurations to ensure efficient geospatial data processing and analysis.
  - Early Issue Detection: Monitoring Zilliz helps in the early detection of system issues, such as software bugs, hardware failures, or network problems. This proactive approach allows you to address problems before they impact the reliability and availability of your geospatial analytics applications.
  - Resource Management: Monitoring enables you to allocate resources appropriately and avoid unexpected outages or performance degradation by tracking CPU, memory, and storage usage patterns.
  - Security: Detect security breaches or unauthorized access in your Zilliz environment, which is also crucial to comply with data security regulations and protect sensitive geospatial data.
  - Scalability: By monitoring usage trends and resource consumption, you can make informed decisions about when and how to scale your Zilliz infrastructure to accommodate increasing workloads.

  ### What’s included in this quickstart?

  The Zilliz quickstart installs preconfigured observability solutions, including:
  - High-value alerts that can help you identify and resolve problems early.
  - Informative dashboards that provide you with a visual representation of the performance of your systems and applications.

summary: |
  Gain actionable information from monitoring Zilliz to increase resource efficiency and cut costs.
icon: logo.png
level: New Relic
authors:
  - New Relic
title: Zilliz
documentation:
  - name: LangChain Vector Database integration documentation
    description: |
      Implement monitoring and instrumentation for your LangChain Vector Database, and ensure that your LangChain Vector Database data is integrated into New Relic for effective performance analysis and insights.
    url: https://github.com/newrelic/nr-openai-observability
dataSourceIds:
  - langchain-vectordb
keywords:
  - langchain-vectordb
  - mlops
  - NR1_addData
dashboards:
  - langchain-vectordb
alertPolicies:
  - langchain-vectordb
